---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base:latest

.installGo15: &installGo15 |
  mkdir /go15
  yum install -y gcc
  curl https://dl.google.com/go/go1.15.5.linux-amd64.tar.gz  | tar -zxC /go15
  ln -s /go15/go/bin/go /usr/bin/go15
  go15 get ./...
.copyCerts: &copyCerts |
  #using service cert of ermis, just for testing purposes
  echo "$HOSTCERT" > /etc/ssl/certs/hostcert.pem
  echo "$HOSTKEY" > /etc/ssl/certs/hostkey.pem
  echo "$CACERT" > /etc/ssl/certs/ca.pem
  

build-go15:
  stage: prebuild
  script:
    - *installGo15
    - go15 build -race ./...

test-go15:
  stage: test
  script:
    - *installGo15
    - *copyCerts
    - go15 test -v -cover ./tests/ci/...
    - go15 test -race ./tests/ci/...

bench-go15:
  stage: test
  script:
    - *installGo15
    - go15 test ./tests/benchmarking/... -bench=. -benchmem
    - go15 test ./tests/benchmarking/... -bench=. -benchmem -race

