---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base:latest

include:
  - 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'
#  - project: lb-experts/golbclient
#    file: .gitlab-ci_koji.yml
  - project: lb-experts/golbclient
    file: .gitlab-ci_go.yml
    ref: gitlab_go

variables:
  KOJI_TAG_8: .el8
  KOJI_TAG_7: .ai7
  KOJI_TAG_6: .ai6

before_script:
  - yum -y install rpm-build rpmdevtools
  - mkdir -p /go/src/gitlab.cern.ch/lb-experts
  - if [ -d /builds ] ;  then  export PREFIX=/builds  ;  fi
  - ln -s $PREFIX/lb-experts/golbclient /go/src/gitlab.cern.ch/lb-experts/golbclient
  - cd /go/src/gitlab.cern.ch/lb-experts/golbclient
  - export SPEC=$(ls *spec)
  - RELEASE=`grep 'Release = "' lbclient.go | awk -F \" '{print $2}'`
  - VERSION=`grep 'Version = "' lbclient.go | awk -F \" '{print $2}'`
  - cat $SPEC | sed "s/#REPLACE_BY_VERSION#/$VERSION/" > $SPEC.tmp
  - cat $SPEC.tmp | sed "s/#REPLACE_BY_RELEASE#/$RELEASE/" > $SPEC
  - export PKG=$(rpm -q --specfile $SPEC --queryformat "%{name}-%{version}\n" | head -n 1)
#  - export PKG_REL6=$(rpm -q --define "dist .ai6" --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)
#  - export PKG_REL7=$(rpm -q --define "dist .ai7" --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)
#  - export PKG_REL8=$(rpm -q --define "dist .el8" --specfile $SPEC --queryformat "%{name}-%{version}-%{release}\n" | head -n 1)

.installGo12: &installGo12 |
  mkdir /go12
  yum -y install git gcc
  curl https://dl.google.com/go/go1.12.17.linux-amd64.tar.gz  | tar -zxC /go12
  ln -s /go12/go/bin/go /usr/bin/go12
  export GOPATH=/go
  go12 get ./...

.openTestPorts: &openTestPorts |
  yum install iproute nmap-ncat git gcc -y
  nc -l      -p           22        &
  nc -l      -p           21        &
  nc -l      -p           2811      &
  nc -l      -p           80        &
  nc -l      -p           922       &
  nc -l -u   -p           922       &
  nc -l  127.0.0.1 202              &
  sleep 1
  cat /proc/net/tcp
  cat /proc/net/tcp6
  if [ -d /builds ] ;  then  export PREFIX=/builds  ;  fi
  ln -s $PREFIX/lb-experts/golbclient/scripts/lemon-cli /usr/sbin/lemon-cli
  ln -s $PREFIX/lb-experts/golbclient/scripts/collectdctl /usr/bin/collectdctl

test-go12:
  stage: test
  before_script:
    - *openTestPorts

test-go13:
  stage: test
  before_script:
    - *openTestPorts


test-lbclient-binary:
  stage: test
  script:
    - *installGo12
    - echo "load constant 50000" > /usr/local/etc/lbclient.conf
    - echo "lbalias=test.cern.ch" > /usr/local/etc/lbaliases
    - cd /builds/lb-experts/golbclient
    - go12 run lbclient.go | grep -Pzo ".1.3.6.1.4.1.96.255.1(\n)integer(\n)50000" | if [ $(wc -l) -eq 3 ]; then true; else false; fi
    - echo "lbalias=test2.cern.ch" >> /usr/local/etc/lbaliases
    - echo "load constant 40000" >> /usr/local/etc/lbclient.conf.test2.cern.ch
    - go12 run lbclient.go | grep -Pzo ".1.3.6.1.4.1.96.255.1(\n)string(\n)test2.cern.ch=40000,test.cern.ch=50000" | if [ $(wc -l) -eq 3 ]; then true; else false; fi

build_rpm:
  stage: rpm
  script:
    - *installGo12
    - cd $PREFIX/lb-experts/golbclient
    - go12 mod vendor
    - mkdir SOURCES version
    - tar cvf SOURCES/$PKG.tg  --exclude SOURCES --exclude .git --exclude .koji --exclude .gitlab-ci.yml --exclude go.mod --exclude go.sum --transform "s||$PKG/|" .
    - gzip -c SOURCES/$PKG.tg > SOURCES/$PKG.tgz
    - rm -rf SOURCES/$PKG.tg
    - rpmbuild -bs --define "_topdir $(pwd)" -D "dist .ai6" $SPEC
    - rpmbuild -bs --define "_topdir $(pwd)" -D "dist .ai7" $SPEC
    - rpmbuild -bs --define "_topdir $(pwd)" -D "dist .el8" $SPEC
  artifacts:
    paths:
      - SRPMS/
    expire_in: 1 week


