---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base:20180516

stages:
  - build
  - test
  - build_rpm
  - koji_scratch
  - koji_install
  - koji
  - deploy_qa
  - deploy_prod

.installKoji: &installKoji |
  yum -y install koji
  KOJI_USER=${KOJI_USER:-lbbuild}
  KOJI_PASSWORD=${KOJI_PASSWORD:-$LBBUILD_PASSWORD}
  echo $KOJI_PASSWORD | kinit $KOJI_USER@CERN.CH
  klist
  printf "[koji]\nserver = https://kojihub.cern.ch/kojihub\nweburl = https://koji.cern.ch/koji\ntopurl = https://koji.cern.ch/kojifiles\nkrb_canon_host = no\nkrb_rdns = False" > .koji
  export KOJI_TAG6=${KOJI_TAG6:-ai6} KOJI_TAG7=${KOJI_TAG7:-ai7} KOJI_TAG8=${KOJI_TAG8:-lb8}

  ALL_TARGETS=""
  [ "${PKG_REL6}" != "" ] && ALL_TARGETS+="${KOJI_TAG6}_${PKG_REL6}"
  [ "${PKG_REL7}" != "" ] && ALL_TARGETS+=" ${KOJI_TAG7}_${PKG_REL7}"
  [ "${PKG_REL8}" != "" ] && ALL_TARGETS+=" ${KOJI_TAG8}_${PKG_REL8}"
  echo "Building for $ALL_TARGETS"

rpmlint:
  stage: build_rpm
  script:
    - yum -y install rpmlint
    - rpmlint *.spec
  allow_failure: true

kojicheck:
  stage: koji_scratch
  script:
    - *installKoji
    - CHECK=""
    - if [ "${PKG_REL6}" != "" ] ; then CHECK="${PKG_REL6}|"; fi
    - if [ "${PKG_REL7}" != "" ] ; then CHECK+="${PKG_REL7}|"; fi
    - if [ "${PKG_REL8}" != "" ] ; then CHECK+="${PKG_REL8}|"; fi
    - if [ "$CHECK" != "" ] ; then CHECK=${CHECK%?} ; fi
    - echo "Checking if $CHECK exists"
    - if koji --config=.koji search -r build $PKG | egrep  "$CHECK" ; then exit 1; fi
  allow_failure: true

kojiscratch:
  stage: koji_scratch
  script:
    - *installKoji
    - mkdir -p logs RPMS
    - for data in ${ALL_TARGETS[@]};
      do my_array=(${data/_/ });
      echo "Ready to do $data";
      echo "koji build --wait --scratch ${my_array[0]} SRPMS/${my_array[1]}.src.rpm";
      koji --config=.koji build --wait --scratch ${my_array[0]}  SRPMS/${my_array[1]}.src.rpm | tee logs/koji_${my_array[0]};
      kojiId=$(cat logs/koji_${my_array[0]} | grep "Created task:" | awk '{print $3}' );
      koji --config=.koji download-task ${kojiId};
      rm -f *.src.rpm;
      mv *.rpm RPMS/;
      done
  artifacts:
    paths:
      - RPMS/
    expire_in: 1 week


kojiinstall6:
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  stage: koji_install
  script:
    - if [ "${PKG_REL6}" != "" ] ; then
        echo "Installing on 6 (${PKG_REL6})";
        ls  RPMS/${PKG_REL6}*.rpm;
        yum install -y RPMS/${PKG_REL6}*.rpm;
      fi

kojiinstall7:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  stage: koji_install
  script:
    - if [ "${PKG_REL7}" != "" ] ; then
        echo "Installing on 7 (${PKG_REL7})";
        ls  RPMS/${PKG_REL7}*.rpm;
        yum install -y RPMS/${PKG_REL7}*.rpm;
      fi

kojiinstall8:
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  stage: koji_install
  script:
    - if [ "${PKG_REL8}" != "" ] ; then
        echo "Installing on 8 (${PKG_REL8})";
        ls  RPMS/${PKG_REL8}*.rpm;
        yum install -y RPMS/${PKG_REL8}*.rpm;
      fi

koji:
  stage: koji
  script:
    - *installKoji
    - for data in ${ALL_TARGETS[@]};
      do my_array=(${data/_/ });
      echo "koji build --wait ${my_array[0]} SRPMS/${my_array[1]}.src.rpm";
      koji --config=.koji build --wait ${my_array[0]}  SRPMS/${my_array[1]}.src.rpm ;
      done
  only:
    - tags

tag_qa:
  stage: deploy_qa
  when: manual
  only:
    - tags
  script:
    - *installKoji
    - for data in ${ALL_TARGETS[@]};
      do my_array=(${data/_/ });
      echo "koji --config=.koji tag-pkg ${my_array[0]}-qa  ${my_array[1]}";
      koji --config=.koji tag-pkg ${my_array[0]}-qa  ${my_array[1]} ;
      done
  allow_failure: false

tag_prod:
  stage: deploy_prod
  when: manual
  only:
    - tags
  script:
    - *installKoji
    - for data in ${ALL_TARGETS[@]};
      do my_array=(${data/_/ });
      echo "koji --config=.koji tag-pkg ${my_array[0]}-stable  ${my_array[1]}";
      koji --config=.koji tag-pkg ${my_array[0]}-stable  ${my_array[1]} ;
      done

