# Builder
FROM golang:latest as builder
WORKDIR /lbclient
# LBclient
COPY lbclient.go .
COPY utils ./utils
ADD lbalias ./lbalias
COPY go.mod .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lbclient .
# Test APP
CMD ["/lbclient", "--help"]

# Minified image
FROM cern/cc7-base:latest
# LBclient
ENV lbclient_conf_location=/usr/local/etc
COPY deployment/config/default/lbaliases $lbclient_conf_location/
COPY deployment/config/default/lbclient.conf $lbclient_conf_location/
COPY --from=builder /lbclient /usr/local/sbin/lbclient
# SNMP
RUN yum -y install net-snmp net-snmp-utils checkpolicy policycoreutils-python
ENV se-policy-location=/usr/share/selinux/targeted/lbclient.pp
WORKDIR /deployment
COPY deployment/config/src/cc7-lbclient.te lbclient.te
RUN ls .
RUN checkmodule -M -m -o lbclient.mod lbclient.te
RUN ls .
RUN semodule_package -m lbclient.mod -o lbclient.pp
RUN semodule -i lbclient.pp 
# Test configuration
RUN /usr/bin/snmpget -d -v 3 -u loadbalancing -l authNoPriv -a MD5 localhost .1.3.6.1.4.1.96.255.1 
CMD ["/lbclient", "--help"]
