#!/bin/bash

## Find given metric in array
find_in_array() {
        array=("${!2}")
        find="${!1}"

        for metric in "${array[*]}"
	        do
	            if [[ "${3}" == "all" ]]; then
	                printf "lxplus801.cern.ch/${metric}"
	            else
	                printf "lxplus801.cern.ch/${metric}" | grep -w "$find" | awk '{print $2" "$3}'
	            fi
	        done
}

## Get the supplied metrics
# Static metrics
db=(
	"vmem/vmpage_number-writeback_temp value=0.000000e+00"
	"cpu/percent-idle value=9.844851e+01"
	"load/load-relative value=10.01e+01"
	"cpu/percent-system value=3.356831e+01"
	"test in=1.960003e+00\ntest out=3.241338e+01"
)

## Unknown DB
db_unknown=(
    "cpu/percent-idle"
    "memory/memory-cached"
)

## Okay DB
db_okay=(
    "cpu/percent-system"
)

## Error DB
db_error=(
    "vmem/vmpage_number-writeback"
)

## Warning DB
db_warning=(
    "interface-eth0/if_dropped"
)

mode=${1}
metric=${2}

## Iterate over the supplied metrics and find a value if they exist
OIFS=$IFS
IFS=$'\n'

if [[ ${1} == "listval" ]]; then
    case "${2:6:10}" in
        "UNKNOWN"|"unknown") find_in_array metric db_unknown[*] all ;;
        "OKAY"|"okay") find_in_array metric db_okay[*] all ;;
        "ERROR"|"error") find_in_array metric db_error[*] all ;;
        "WARNING"|"warning") find_in_array metric db_warning[*] all ;;
    esac
else
    find_in_array metric db[*]
fi


IFS=${OIFS}
