#!/bin/bash

oper=${1}
object=${2}
mountpoint=${3}

function errorExit(){
    errormessage="${1}"
    echo "${mountpoint}: eos.mgmurl: ${errormessage}" >&2
    exit 1
}

function normalExit(){
    machinename=${mountpoint////}
    echo -n "root://${machinename}.cern.ch"
    exit 0
}

if [[ ${oper} == "get" ]]; then
    if [[ ${object} == "eos.mgmurl" ]]; then
        case "${mountpoint}" in
            "/eos/home-t") errorExit "Transport endpoint is not connected"  ;;
            "/eos/project-o") errorExit "Operation not supported" ;;
            "/eos/home-n") errorExit "No such attribute" ;;
            "/eos/home-i") errorExit "Input/output error" ;;
	    *) normalExit ;;
        esac
    fi
fi

exit 126
